services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=inventory_management

    volumes:
      # Volume para garantir que os dados não sejam perdidos após o desligamento do container
      - ./data/postgres:/var/lib/postgresql/data
      # Volume para garantir que os scripts sejam executados na inicialização do container.
      # Caso o script já tenha sido executado e após isto foi modificado novamente,
      # será necessário excluir tudo dentro do diretório ./data/postgres,
      # para que assim ao subir o container o script seja executado novamente.
      - ./postgres/scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:

